import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { LangBiTeDSLGeneratedModule, LangBiTeDSLGeneratedSharedModule } from './generated/module.js';
import { EthicsMlValidator, registerValidationChecks } from './langbite-dsl-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type EthicsMlAddedServices = {
    validation: {
        EthicsMlValidator: EthicsMlValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type EthicsMlServices = LangiumServices & EthicsMlAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const EthicsMlModule: Module<EthicsMlServices, PartialLangiumServices & EthicsMlAddedServices> = {
    validation: {
        EthicsMlValidator: () => new EthicsMlValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createEthicsMlServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    EthicsMl: EthicsMlServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        LangBiTeDSLGeneratedSharedModule
    );
    const EthicsMl = inject(
        createDefaultModule({ shared }),
        LangBiTeDSLGeneratedModule,
        EthicsMlModule
    );
    shared.ServiceRegistry.register(EthicsMl);
    registerValidationChecks(EthicsMl);
    return { shared, EthicsMl };
}
